name: intrinsic_props
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyqt
  - pyqtgraph
  - jupyterlab
  - ipykernel
  - openpyxl
  - pip
  - pip:
    - pyabf
